[build-system]
requires = ["setuptools>=45", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pandas-plus"
version = "0.1.0"
description = "High-performance extension package for pandas with fast groupby operations"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
keywords = ["pandas", "groupby", "performance", "numba", "numpy", "data-analysis"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "numpy>=1.19.0",
    "pandas>=1.3.0",
    "numba>=0.56.0",
    "polars>=0.15.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-xdist",
    "black",
    "flake8",
    "isort",
    "mypy",
    "bandit",
    "safety",
]
plotting = [
    "matplotlib>=3.0.0",
    "seaborn>=0.11.0",
]
test = [
    "pytest>=6.0",
    "pytest-xdist",
]

[project.urls]
Homepage = "https://github.com/eoincondron/pandas-plus"
"Bug Reports" = "https://github.com/eoincondron/pandas-plus/issues"
Source = "https://github.com/eoincondron/pandas-plus"
Documentation = "https://github.com/eoincondron/pandas-plus/blob/main/README.md"

[project.scripts]
pandas-plus = "pandas_plus.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["pandas_plus*"]

[tool.setuptools.package-data]
"pandas_plus" = ["py.typed"]

[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["pandas_plus"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "build", "dist"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
