{% set name = "groupby-lib" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv
  entry_points:
    - groupby-lib = groupby_lib:__main__

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10
    - numpy >=1.19.0
    - pandas >=1.3.0
    - numba >=0.56.0
    - polars >=0.15.0
    - pyarrow >=1.0.0

test:
  imports:
    - groupby_lib
    - groupby_lib.groupby
    - groupby_lib.groupby.core
    - groupby_lib.groupby.numba
    - groupby_lib.plotting
    - groupby_lib.nanops
    - groupby_lib.util
  commands:
    - python -c "import groupby_lib; print('groupby-lib imported successfully')"
  requires:
    - pytest >=6.0
    - pytest-xdist
  source_files:
    - tests/
  commands:
    - python -m pytest tests/ -v --tb=short

about:
  home: https://github.com/eoincondron/groupby-lib
  license: MIT
  license_family: MIT
  summary: High-performance extension package for pandas with fast groupby operations
  description: |
    groupby-lib enhances pandas' groupby functionality with optimized implementations 
    that leverage NumPy arrays and Numba's just-in-time compilation for significant 
    performance improvements. The package is designed to work seamlessly with pandas 
    DataFrames and Series while providing additional flexibility for various array types.
  doc_url: https://github.com/eoincondron/groupby-lib
  dev_url: https://github.com/eoincondron/groupby-lib

extra:
  recipe-maintainers:
    - eoincondron