{% set name = "kungfu-pandas" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eoincondron/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6833d9aef2cc00b536cd2a7707117b837ef351f35e9cae9e790393e01cd7b3ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - kungfu-pandas = kungfu_pandas.__main__:main

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.10
    - numpy >=1.19.0
    - pandas >=1.3.0
    - numba >=0.56.0
    - polars >=0.15.0

test:
  imports:
    - kungfu_pandas
    - kungfu_pandas.groupby
    - kungfu_pandas.groupby.core
    - kungfu_pandas.groupby.numba
    - kungfu_pandas.plotting
    - kungfu_pandas.nanops
    - kungfu_pandas.util
  commands:
    - python -c "import kungfu_pandas; print('kungfu-pandas imported successfully')"
    - kungfu-pandas --help
  requires:
    - pytest >=6.0
    - pytest-xdist

about:
  home: https://github.com/eoincondron/kungfu-pandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: High-performance extension package for pandas with fast groupby operations
  description: |
    kungfu-pandas enhances pandas' groupby functionality with optimized implementations 
    that leverage NumPy arrays and Numba's just-in-time compilation for significant 
    performance improvements. The package is designed to work seamlessly with pandas 
    DataFrames and Series while providing additional flexibility for various array types.
  doc_url: https://github.com/eoincondron/kungfu-pandas/blob/main/README.md
  dev_url: https://github.com/eoincondron/kungfu-pandas

extra:
  recipe-maintainers:
    - eoincondron